### ISSUE TITLE
production deployment

### ISSUE THREAD

**Issue by co0p** [brotherhood-of-recursive-descent/froggo#19]
in order to showcase the game, it should be deployed to a website allowing others to play the game

- [x] deployment step in pipeline exists
- [x] compilation to wasm
- [x] github page for game exists
- [x] deployment on changes to main when all tests are passed

**Comment by co0p** [comment]
@jevbelikov SUCCESS ... we have a working CICD pipeline with deployment to the web!

![image](https://github.com/user-attachments/assets/1086af5c-3aeb-4c74-8e5f-c7c80d8b5d51)

**Comment by jevbelikov** [comment]
great!  updated project description
