### ISSUE TITLE
draw green rectangle

### ISSUE THREAD

**Issue by co0p** [brotherhood-of-recursive-descent/froggo#2]
models the frog game object

- [x] 256x256 green
- [x] grey border (border)
- [x] location: bottom centred

**Comment by co0p** [comment]
@jevbelikov please see https://github.com/brotherhood-of-recursive-descent/froggo/commit/e61bf35620c5799c2178ef542fc5350cee5ef607#diff-e97601ea99d87e173bc8ce251693eff2b666106820a876f9756a586a0d7cf3c3 ... to implement the rectancle

**Comment by co0p** [comment]
@jevbelikov and then add the component to the player -> game/entity/player.go https://github.com/brotherhood-of-recursive-descent/froggo/commit/e61bf35620c5799c2178ef542fc5350cee5ef607#diff-25b8ce1797ea345976e775759f488acf1bea7a43b14e7c02f0349f326e2d069b

**Comment by jevbelikov** [comment]
added stuff but still wip
